extends RefCounted
# Park props generated by tools/blender/build_park_assets.py (docs/futuro/17 §2.2).
# Each assets/parque/<name>.glb holds meshes named "<lod>[_<variant>][_<role>]": lod "hd"
# (Ultra) or "lo" (other profiles); role "glass", "bulb" or "trunk" (tree wood), or none for
# opaque geometry (foliage in trees).
# Files are read at run time with GLTFDocument, so no import step is needed to play from source.

const DIR = "res://assets/parque/"
static var cache = {}

# {"<variant>": {"<role>": ArrayMesh}} for one level of detail, or {} if the file is missing.
static func meshes(asset: String, lod: String) -> Dictionary:
	var key = asset + ":" + lod
	if cache.has(key): return cache[key]
	var out = {}
	var path = DIR + asset + ".glb"
	if FileAccess.file_exists(path):
		var document = GLTFDocument.new()
		var state = GLTFState.new()
		if document.append_from_file(path,state) == OK:
			# Only the requested level of detail becomes an ArrayMesh: generate_scene() would upload
			# every mesh in the file (hd included) to the GPU.
			var gltf_meshes = state.get_meshes()
			for gltf_node in state.get_nodes():
				if gltf_node.mesh < 0: continue
				var parts = String(gltf_node.resource_name).split("_")
				if parts[0] != lod: continue
				var variant = parts[1] if parts.size() > 1 and parts[1].is_valid_int() else ""
				var role = parts[-1] if parts[-1] in ["glass","bulb","trunk","water","spray","windows"] else ""
				if not out.has(variant): out[variant] = {}
				out[variant][role] = gltf_meshes[gltf_node.mesh].mesh.get_mesh()
	cache[key] = out
	return out

static func available(asset: String) -> bool:
	return FileAccess.file_exists(DIR + asset + ".glb")
